gif_delay = 30
num_cols = 21
middle_y_pos = -5
update_count = 50
update_delay = 10
update_int = 10
bbox_multiplier = 1.5
font_size = 0.8
create_sprites = True
show_fps = False
auto_update = True
show_saved_frame = True
demo = True  # Default value
