gif_delay = 60
num_cols = 21
middle_y_pos = -5
update_count = 100
update_delay = 1
update_int = 2
bbox_multiplier = 1.5
font_size = 0.8
create_sprites = True
show_fps = False
auto_update = False
show_saved_frame = True
demo = True  # Default value
