gif_delay = 60
num_cols = 21
middle_y_pos = -5
update_count = 50
update_delay = 0
update_int = 5
bbox_multiplier = 1.5
font_size = 0.8
create_sprites = False
show_fps = False
auto_update = True
show_saved_frame = True
demo = True  # Default value
auto_exposure_time = 1000
gain = 10
min_face_size = 100
jump_threshold = 50